version: "3.7"

services:
  security:
    build: .
    network_mode: host
    environment:
      - EXTERNAL_CVE_VULNERABILITY_DB=${EXTERNAL_CSV_VULNERABILITY_DB:-https://github.com/nuvla/vuln-db/blob/main/databases/all.aggregated.csv.gz?raw=true}
      - EXTERNAL_CVE_VULNERABILITY_DB_UPDATE_INTERVAL=${EXTERNAL_CVE_VULNERABILITY_DB_UPDATE_INTERVAL:-86400}
      - SECURITY_SCAN_INTERVAL=${SECURITY_SCAN_INTERVAL:-300}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
    labels:
      - nuvlaedge.component=True
      - nuvlaedge.deployment=production
